apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        # This image name will be replaced by Jenkins
        image: dummy-app:latest
        # This is CRITICAL for a local cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 1
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
